Repository J0kk3/ATM, pull requests merged in 2024-01, with the labels that each got.

#17 Account Class - Draft
  Account.cpp
  Account.h
Labels: Konton & Saldo

#18 Currency class
  Currency.cpp
  Currency.h
Labels: Konton & Saldo, Överföring, Växla Pengar

#20 Close #1, #5 & #6
  .vscode/settings.json
  Main.cpp
Labels: Navigation - Huvudmeny

#24 Added dynamic account creation
  Main.cpp
Labels: Konton & Saldo

#25 Iteration 1: Reworked main for better logic. Created Menu class and g…
  ATM.vcxproj
  Account.cpp
  Account.h
  Main.cpp
  Menu.cpp
  Menu.h
Labels: Start & Inlogg, Navigation - Huvudmeny, Konton & Saldo

#27 Currency convert
  .vscode/c_cpp_properties.json
  .vscode/launch.json
  .vscode/settings.json
  Currency.cpp
  Currency.h
  Main.cpp
  Menu.cpp
Labels: Växla Pengar

#29 connected-Account-w-Currency_changed-createAccounts
  Account.cpp
  Account.h
  Main.cpp
Labels: Konton & Saldo

#30 Iteration2
  .gitignore
  Account.cpp
  Account.h
  Currency.cpp
  Currency.h
  Main.cpp
  Menu.cpp
  Menu.h
  User.cpp
  User.h
Labels: Överföring, Växla Pengar

#31 Refactoring and added some menu formatting.
  Account.h
  Menu.cpp
  User.cpp
  User.h
Labels: Navigation - Huvudmeny, Växla Pengar
